### PR TITLE
Add rough tutorial

### PR DESCRIPTION
**Pull request by LiteHell**
Although it needs to be revisied (in sense of design) a lot in the future, It's tutorial anyway.

### CODE REVIEW

**Review by firekann — CHANGES_REQUESTED** [review]
Need a code that allows skipping at the beginning or in the middle of the tutorial.

**Comment by LiteHell** [comment]
Forced-pushed to sync with main branch

**Review by firekann — APPROVED** [review]
LGTM

**Review by boulce — APPROVED** [review]
LGTM

**Pull request merged**
